version: '2'
services:
    mytwentyonepoints-app:
        image: mytwentyonepoints
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mytwentyonepoints-postgresql:5432/MyTwentyOnePoints
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mytwentyonepoints-postgresql:
        extends:
            file: postgresql.yml
            service: mytwentyonepoints-postgresql
